// wordladder_words.js
// PuzzlePilot approved Word Ladder vocabulary.
//
// Proper classic Word Ladder rules:
// - Start and target words are the same length
// - Change exactly one letter per move
// - No adding, removing or rearranging letters
// - Every submitted word must appear in this approved list
//
// Pack 1 currently uses four-letter words.
// The vocabulary is deliberately broad enough to allow
// alternative routes without filling the game with obscure words.

const words = [
    'able', 'ache', 'acid', 'acne', 'acts', 'aged', 'ages', 'aide',
    'aims', 'aloe', 'also', 'amid', 'anti', 'arch', 'area', 'arms',
    'army', 'arts', 'asks', 'atom', 'aunt', 'auto', 'away', 'axis',
    'baby', 'back', 'bake', 'bald', 'bale', 'ball', 'band', 'bank',
    'bare', 'bark', 'barn', 'base', 'bass', 'bath', 'bear', 'beat',
    'been', 'beer', 'bees', 'bell', 'belt', 'bend', 'bent', 'best',
    'bias', 'bike', 'bill', 'bind', 'bird', 'bite', 'blob', 'blow',
    'blue', 'boat', 'body', 'boil', 'bold', 'bomb', 'bond', 'bone',
    'bony', 'book', 'boom', 'boot', 'bore', 'born', 'boss', 'both',
    'bowl', 'boys', 'brag', 'brew', 'brow', 'bulb', 'bulk', 'bump',
    'burn', 'bush', 'busy', 'cafe', 'cage', 'cake', 'calf', 'call',
    'calm', 'came', 'camp', 'caps', 'card', 'care', 'cart', 'case',
    'cash', 'cast', 'cave', 'cell', 'cent', 'chat', 'chef', 'chin',
    'chip', 'city', 'clap', 'claw', 'clay', 'clot', 'club', 'clue',
    'coal', 'coat', 'code', 'coin', 'cold', 'come', 'cook', 'cool',
    'cope', 'copy', 'cord', 'core', 'corn', 'cost', 'crab', 'cram',
    'crew', 'crop', 'cube', 'cure', 'curl', 'cute', 'cyst', 'damp',
    'dare', 'dark', 'dart', 'dash', 'data', 'date', 'dawn', 'days',
    'dead', 'deal', 'dear', 'debt', 'deed', 'deep', 'deer', 'demo',
    'deny', 'desk', 'dial', 'died', 'dies', 'diet', 'dirt', 'dish',
    'dive', 'dock', 'does', 'dogs', 'doll', 'done', 'doom', 'door',
    'dose', 'dove', 'down', 'drag', 'draw', 'drew', 'drip', 'drop',
    'drug', 'drum', 'duck', 'duct', 'duel', 'dull', 'duly', 'dump',
    'dust', 'duty', 'each', 'earn', 'ears', 'ease', 'east', 'easy',
    'edge', 'else', 'ends', 'envy', 'even', 'ever', 'evil', 'exit',
    'eyed', 'eyes', 'face', 'fact', 'fail', 'fair', 'fake', 'fall',
    'fame', 'fang', 'farm', 'fast', 'fate', 'fear', 'feed', 'feel',
    'fees', 'feet', 'fell', 'felt', 'file', 'fill', 'film', 'find',
    'fine', 'fire', 'firm', 'fish', 'five', 'flag', 'flap', 'flat',
    'flea', 'fled', 'flew', 'flip', 'flow', 'foci', 'fold', 'folk',
    'fond', 'food', 'fool', 'foot', 'fork', 'form', 'fort', 'foul',
    'four', 'free', 'frog', 'from', 'fuel', 'full', 'fund', 'fury',
    'gain', 'game', 'gate', 'gave', 'gaze', 'gear', 'gems', 'gene',
    'gets', 'gift', 'girl', 'give', 'glad', 'glow', 'glue', 'goal',
    'goes', 'gold', 'golf', 'gone', 'good', 'gown', 'grab', 'gray',
    'grew', 'grey', 'grin', 'grip', 'grow', 'guns', 'hail', 'hair',
    'half', 'hall', 'halt', 'hand', 'hang', 'hard', 'hare', 'harm',
    'hate', 'have', 'head', 'heal', 'heap', 'hear', 'heat', 'heed',
    'heel', 'held', 'hell', 'help', 'herd', 'here', 'hero', 'hers',
    'hide', 'high', 'hike', 'hill', 'hint', 'hire', 'hive', 'hold',
    'hole', 'holy', 'home', 'hook', 'hope', 'horn', 'host', 'hour',
    'huge', 'hung', 'hunt', 'hurt', 'icon', 'idea', 'idle', 'inch',
    'into', 'iron', 'item', 'jack', 'jaws', 'jazz', 'jest', 'join',
    'joke', 'joys', 'jump', 'jury', 'just', 'keen', 'keep', 'kept',
    'kick', 'kill', 'kind', 'king', 'kiss', 'knee', 'knew', 'knot',
    'know', 'lack', 'lads', 'lady', 'laid', 'lake', 'lamb', 'lamp',
    'land', 'lane', 'last', 'late', 'laws', 'lazy', 'lead', 'left',
    'legs', 'lend', 'lent', 'less', 'lest', 'lies', 'life', 'lift',
    'like', 'limb', 'lime', 'line', 'link', 'lion', 'lips', 'list',
    'live', 'load', 'loan', 'lock', 'logo', 'long', 'look', 'lord',
    'lose', 'loss', 'lost', 'loud', 'love', 'luck', 'lump', 'lust',
    'made', 'maid', 'mail', 'main', 'make', 'male', 'many', 'mark',
    'mass', 'mate', 'maze', 'meal', 'mean', 'meat', 'meet', 'melt',
    'menu', 'mere', 'mess', 'mild', 'mile', 'milk', 'mill', 'mind',
    'mine', 'mint', 'miss', 'mist', 'mode', 'mole', 'monk', 'mood',
    'moon', 'more', 'moss', 'most', 'moth', 'move', 'much', 'must',
    'nail', 'name', 'navy', 'near', 'neck', 'need', 'nest', 'news',
    'next', 'nice', 'nine', 'none', 'nose', 'note', 'oath', 'oats',
    'obey', 'okay', 'once', 'ones', 'only', 'onto', 'open', 'oral',
    'ours', 'oven', 'over', 'pace', 'pack', 'page', 'paid', 'pain',
    'pair', 'pale', 'palm', 'park', 'part', 'pass', 'past', 'path',
    'pawn', 'peak', 'pear', 'pest', 'pick', 'pile', 'pill', 'pine',
    'pink', 'pint', 'pipe', 'pity', 'plan', 'play', 'plea', 'plot',
    'plug', 'plum', 'plus', 'poem', 'pole', 'poll', 'pond', 'pony',
    'pool', 'poor', 'port', 'pose', 'post', 'pour', 'pray', 'prey',
    'pull', 'pump', 'pure', 'push', 'race', 'rage', 'rain', 'rang',
    'rank', 'rare', 'rate', 'rays', 'read', 'real', 'rear', 'reef',
    'rent', 'rest', 'ribs', 'rice', 'rich', 'ride', 'ring', 'ripe',
    'rise', 'risk', 'road', 'roar', 'robe', 'rock', 'rode', 'role',
    'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rosy', 'rows',
    'ruby', 'rude', 'ruin', 'rule', 'runs', 'rush', 'safe', 'said',
    'sail', 'sake', 'sale', 'salt', 'same', 'sand', 'sang', 'sank',
    'save', 'says', 'scar', 'seal', 'seas', 'seat', 'seed', 'seek',
    'seem', 'seen', 'sees', 'self', 'sell', 'semi', 'send', 'sent',
    'shed', 'shin', 'ship', 'shop', 'shot', 'show', 'shut', 'sick',
    'side', 'sigh', 'sign', 'silk', 'sill', 'sing', 'sire', 'site',
    'size', 'skin', 'slap', 'slim', 'slip', 'slow', 'snow', 'sobs',
    'sock', 'soda', 'sofa', 'soft', 'soil', 'sold', 'sole', 'some',
    'song', 'sons', 'soon', 'sore', 'sort', 'soul', 'spin', 'spot',
    'stab', 'stag', 'star', 'stay', 'stem', 'step', 'stir', 'stop',
    'such', 'suit', 'sums', 'sunk', 'sure', 'swan', 'taco', 'tail',
    'take', 'tale', 'talk', 'tall', 'tank', 'tape', 'task', 'team',
    'tear', 'tell', 'tend', 'tens', 'tent', 'term', 'test', 'text',
    'than', 'that', 'them', 'then', 'they', 'thin', 'this', 'thus',
    'tide', 'tidy', 'tied', 'ties', 'till', 'time', 'tiny', 'tips',
    'toes', 'told', 'toll', 'tomb', 'tone', 'took', 'tool', 'tore',
    'torn', 'tour', 'town', 'trap', 'tree', 'trim', 'trip', 'trot',
    'true', 'tube', 'tune', 'turn', 'twin', 'type', 'ugly', 'unit',
    'upon', 'used', 'user', 'vain', 'vary', 'vase', 'vast', 'veil',
    'vein', 'very', 'vice', 'view', 'vile', 'void', 'vote', 'wage',
    'wait', 'wake', 'walk', 'wall', 'want', 'ward', 'warm', 'wars',
    'wash', 'wave', 'ways', 'weak', 'wear', 'week', 'weep', 'well',
    'went', 'wept', 'were', 'west', 'what', 'when', 'whip', 'whom',
    'wide', 'wife', 'wild', 'will', 'wind', 'wine', 'wing', 'wire',
    'wise', 'wish', 'with', 'woke', 'wolf', 'wood', 'wool', 'word',
    'wore', 'work', 'worn', 'writ', 'yard', 'yarn', 'year', 'yell',
    'your', 'zeal', 'zero', 'zest', 'zinc', 'zone'
];

module.exports = new Set(words);

